# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TSmjrMZbpsqtUlVxaZ9_48OB59ob9fu
"""

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

nb_model = joblib.load('naive_bayes_model(3).pkl')
vectorizer_nb = joblib.load('vectorizer_nb.pkl')

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Remove stopwords from each text in the DataFrame
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

test=pd.read_csv("test_data.csv")

test["CONTEXT"]=test["Headline"]+". "+test["Description"]
test.info()

test['CONTEXT'] = test['CONTEXT'].apply(remove_stopwords)

X_test=test["CONTEXT"]

X_test_tfidf = vectorizer_nb.transform(X_test)

y_pred_nb=nb_model.predict(X_test_tfidf)

y_pred_nb

labels = {0: "Business",1: "Politics",2: "Sport",3: "Tech"}
final=pd.DataFrame({"predicted":y_pred_nb})
final["predicted"]=final["predicted"].apply(lambda x:labels[x])

final.to_csv("q2_submission.csv")

